### PR TITLE
Update lint-staged to v8

### LINKED ISSUE #63: Update lint-staged to v8
## 🐛 Bug Report

When trying to commit partially staged files, our linting adds the entire file during `precommit` without saying anything. I often accidentally commit lines I purposefully excluded because of this and end up with messy commits (or I have to re-write my local history).

## To Reproduce

- Make some changes to a file
- Run `git add -p`
- Select some lines and not others
- Run `git commit`

## Expected Behavior

My commit should only contain the changes I've staged.

## Actual Results

Your commit will include the lines you excluded

## Solution

We are currently on `lint-staged` v7.1. Support was added for partially staged files in v8.0: https://hackernoon.com/announcing-lint-staged-with-support-for-partially-staged-files-abc24a40d3ff

### PR DESCRIPTION
**Pull request by Patil2099**
This Change fixes #63.

### CODE REVIEW

**Comment by Patil2099** [comment]
@lychyi  This Won't Fail

**Comment by Patil2099** [comment]
@lychyi  It didn't fail

**Comment by NicholasBoll** [comment]
This seems to work from my testing of the fork (`lint-staged` doesn't run as part of the CI and requires a change to a linted file to test).

**Comment by NicholasBoll** [comment]
Thank you @Patil2099!

**Comment by lychyi** [comment]
Thanks for the contribution @Patil2099! And thanks for the verification @NicholasBoll 

🎉

**Pull request merged**
