### PR TITLE
fix(button): Remove inner ring on icon button focus state

### PR DESCRIPTION
**Pull request by anishatulai**
## Summary

Fixes: #1438  

category

---

## Checklist

- [ ] tests are changed or added
- [ ] code has been documented
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](https://workday.github.io/canvas-kit/?path=/story/welcome-dev-docs-api-pattern-guidelines--page)

### CODE REVIEW

**Review by mannycarrera4 — APPROVED** [review]
Nice work on this 🥳

**Comment by NicholasBoll** [comment]
We want to get rid of the ghosting, but not get rid of the ring. It is more obvious to see why in the inverse state tables when a button is focused and toggled on:

Before:
image

After:
image

In the after, you cannot tell there's a focus ring.

This video toggles the before/after.
Changes

**Comment by NicholasBoll** [comment]
I experimented with a different styling approach that would get rid of the ghosting: https://codesandbox.io/s/iconbutton-no-ghosting-6nf1m

**Comment by alanbsmith** [comment]
Thanks for this! Closing this for now. Let's revisit this later.

**Pull request closed without merging**
