### PR TITLE
fix: Header SearchBar fills parent container

### PR DESCRIPTION
**Pull request by JustAboutJeff**
This PR fixes https://github.com/Workday/canvas-kit/issues/476. More specifically, the `SearchInput` component now fills the width of its' parent element as expected 🎉.

## Summary

Responding to a bug report identified in the github issues.

## Checklist

- [x] branch has been rebased on the latest master commit
- [x] tests are changed or added
- [x] `yarn test` passes
- [x] all (dev)dependencies that the module needs is added to its `package.json`
- [x] code has been documented and, if applicable, usage described in README.md
- [x] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

## Additional References

See this gif below to see the CSS change within this PR taking effect. The red border was added to demonstrate the parent container size:

SearchInput

### CODE REVIEW

**Comment by laurenraddatz** [comment]
thank you for the fix!

**Comment by vibdev** [comment]
Playing around a bit with this and I think the issue is in combobox

**Comment by vibdev** [comment]
I opened https://github.com/Workday/canvas-kit/pull/513 as a possible alternate solution that changes combo box. Thoughts?

**Comment by anicholls** [comment]
@JustAboutJeff Thank you for the PR! 👍 The issue actually lives within Combobox, so we're going to merge #513 instead. Closing this in favor of that PR, but let me know if you have any questions/concerns.

**Pull request closed without merging**
