### PR TITLE
fix(toast): Remove transform origin for visual stories

### PR DESCRIPTION
**Pull request by mannycarrera4**
When Chromatic takes its snapshot, the `Toast` hasn't animated into view so the snapshots look empty, by allowing a transform origin of null, we get to have our snapshots back.

### CODE REVIEW

**Comment by NicholasBoll** [comment]
This contains some of the same code as #600 which is against master. Should we just merge `master` forward and close this PR?

**Comment by mannycarrera4** [comment]
Works for me @NicholasBoll

**Comment by mannycarrera4** [comment]
Solved in #600 once we merged master forward into pre release v4

**Comment by anicholls** [comment]
@mannycarrera4 Don't you still need to pass `transformOrigin={null}` for this story? 

FYI, master changes are going in w/ https://github.com/Workday/canvas-kit/pull/623

**Comment by mannycarrera4** [comment]
ah yeah, in that case, I can just delete all the transform origin stuff since that went into master, and pass null to the story

**Pull request closed without merging**
