### PR TITLE
fix(button): Avoid using transition all for buttons

### PR DESCRIPTION
**Pull request by mannycarrera4**
## Summary

Fixes: https://github.com/Workday/canvas-kit/issues/368
## Checklist

- [ ] branch has been rebased on the latest master commit
- [ ] tests are changed or added
- [ ] `yarn test` passes
- [ ] all (dev)dependencies that the module needs is added to its `package.json`
- [ ] code has been documented and, if applicable, usage described in README.md
- [ ] module has been added to `canvas-kit-react` and/or `canvas-kit-css` universal modules, if
      applicable
- [ ] design approved final implementation
- [ ] a11y approved final implementation
- [ ] code adheres to the [API & Pattern guidelines](../API_PATTERN_GUIDELINES.md)

### CODE REVIEW

**Comment by NicholasBoll** [comment]
It is hard to say if this will be a breaking change for anybody. It won't show up on visual regressions since it is a transition...

We may want a note somewhere stating this might change how properties update.

**Comment by mannycarrera4** [comment]
@NicholasBoll i agree, do you have any ideas how we can communicate this?

**Comment by NicholasBoll** [comment]
I think just put the note in the squashed commit message. I think that gets used in changlogs, right? Or do we only use summaries? @anicholls ?

**Comment by anicholls** [comment]
@NicholasBoll @mannycarrera4 We could add a note in the PR summary (merge commit) message

**Pull request merged**
