### PR TITLE
ci: Add project board automations

### PR DESCRIPTION
**Pull request by jaclynjessup**
## Summary

Adding a GitHub action for new project board
- when an issue is opened or reopened status of `New` is added
- when an issue is closed status of `Done` is added
- when an issues is labeled `good first issue` or `help wanted` it is added to the Contribution board
- when an issue is labeled `ready for review `status is set to `In Review`
- when a PR with the branch name `merge/prerelease/minor-into-prerelease/major` is made status is set to `in review` and priority is `Urgent`

category

### CODE REVIEW

**Comment by mannycarrera4** [comment]
If the PR has a `review in progress` but no `ready for review` does it keep it in `in review` ?

**Comment by mannycarrera4** [comment]
Also, does it care about Draft PRs?

**Review by mannycarrera4 — APPROVED** [review]
No blockers from me! Just had questions, this will help a ton!

**Comment by jaclynjessup** [comment]
@mannycarrera4 I did not add any triggers for the removal of a label. So if the issue got `ready for review` first and then removed as `review in progress` was added it should not change the status. Once we nail down the flow of adding labels, assigning reviewers, requesting changes, etc we can button up the board automation.

I don't think this limits draft PRs. I only see a [type](review in progress) when you convert to a draft.

**Comment by mannycarrera4** [comment]
Note, used this PR to accept baseline changes to IE

**Pull request merged**
