### PR TITLE
fix: Update click target for switch

### PR DESCRIPTION
**Pull request by mannycarrera4**
## Summary

Fixes: https://github.com/Workday/canvas-kit/issues/657

The click target is off when the label and and switch are stacked, making it hard to click sometimes. By adding display block, the click target is now the full width of the input.

### CODE REVIEW

**Comment by lychyi** [comment]
@mannycarrera4 Does it fix that issue or just a part of that issue? Using the 'Fixes' keyword will close it. Just making sure this is the only fix for that issue.

**Comment by mannycarrera4** [comment]
@lychyi I believe so, i think we can also set `left: 0` which will shift the input to the left of it's container which has position relative.

**Comment by lychyi** [comment]
@mannycarrera4 Can we base this off of master and target this PR there?

**Comment by mannycarrera4** [comment]
Closing to base off of master instead

**Pull request closed without merging**
