### PR TITLE
docs(action-bar): Add delete action example to ActionBar

### PR DESCRIPTION
**Pull request by RayRedGoose**
## Summary

Resolves: #1627  

PR adds an Action Bar example that uses a Delete Button. 

documentation

Screen Shot 2022-06-07 at 2 31 22 PM

### CODE REVIEW

**Review by mannycarrera4 — APPROVED** [review]

**Comment by mannycarrera4** [comment]
Do we want this off of `prerelease/minor` ?

**Comment by RayRedGoose** [comment]
@mannycarrera4 yes, it's minor change as it's documentation update

**Comment by mannycarrera4** [comment]
ok, want to change the branch?

**Comment by RayRedGoose** [comment]
Ma fault, it's patch change.

**Pull request merged**
