### PR TITLE
chore: Have verify action to wait on visual tests [skip release]

### PR DESCRIPTION
**Pull request by mannycarrera4**
## Summary

For a more accurate verify process, I've added `visual-testing` to the verify step as a dependency.

category

### CODE REVIEW

**Comment by mannycarrera4** [comment]
Screen Shot 2021-12-08 at 9 20 59 AM
after change

**Comment by mannycarrera4** [comment]
Screen Shot 2021-12-08 at 9 38 04 AM
Not bad!

**Comment by mannycarrera4** [comment]
Screen Shot 2021-12-08 at 10 03 23 AM
After cache!

**Comment by NicholasBoll** [comment]
It's sad that Chromatic takes so long, but I do like more accurate reporting of time. Github doesn't charge for minutes, so that's good. The extra time on `visual-testing` is idle time for the Github worker node.

**Review by NicholasBoll — APPROVED** [review]

**Pull request merged**
